"""added participants in db

Revision ID: 3ad9f3aa46cb
Revises: eddeaadd747e
Create Date: 2023-07-10 19:56:07.359585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad9f3aa46cb'
down_revision = 'eddeaadd747e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('participants')

    # ### end Alembic commands ###
