"""change tables

Revision ID: a9f17fb24e55
Revises: 3ad9f3aa46cb
Create Date: 2023-08-08 17:28:23.536221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9f17fb24e55'
down_revision = '3ad9f3aa46cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_club_events')
    op.drop_table('user_uv_events')
    op.drop_table('club_events')
    op.drop_table('utsava_vaibhava_events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utsava_vaibhava_events',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('event_type', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('venue', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('club_events',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('event_type', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('club', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('venue', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('date', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('image_uri', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_uv_events',
    sa.Column('user_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('uv_event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('applied', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_uv_events_ibfk_1'),
    sa.ForeignKeyConstraint(['uv_event_id'], ['utsava_vaibhava_events.id'], name='user_uv_events_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'uv_event_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_club_events',
    sa.Column('user_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('club_event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('applied', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club_event_id'], ['club_events.id'], name='user_club_events_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_club_events_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'club_event_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
