"""lmao

Revision ID: eddeaadd747e
Revises: 0056e66baca8
Create Date: 2023-06-20 16:41:18.664925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddeaadd747e'
down_revision = '0056e66baca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_uri', sa.String(length=50), nullable=True))
        batch_op.drop_column('image')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_uri', sa.String(length=75), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dept', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('venue', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('event_mode', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('date', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('expiration', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('expiration')
        batch_op.drop_column('time')
        batch_op.drop_column('date')
        batch_op.drop_column('event_mode')
        batch_op.drop_column('venue')
        batch_op.drop_column('amount')
        batch_op.drop_column('dept')
        batch_op.drop_column('event_type')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('image_uri')

    with op.batch_alter_table('club_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.BLOB(), nullable=True))
        batch_op.drop_column('image_uri')

    # ### end Alembic commands ###
